### ISSUE TITLE
FT Rates

### ISSUE THREAD

**Issue by werebus** [umts/umass.edu-transit#5]
There were some discrepancies as to what the rates for van trips are supposed to be.  I found the email from June 2013 where they were changed to what's on the website now, but it looks like the FT department might not have updated their internal paperwork.  I'm waiting on Diana to track down which is correct.

**Comment by dfaulken** [comment]
I updated the van 'outside Pioneer Valley' rate to $52 today. https://github.com/umts/umass.edu-transit/commit/b93729e2aa7e27c1066ac53442485ae279f2c188

**Comment by werebus** [comment]
Yup.  The previous debate was actually about the minimum charge.  We changed it from 60 to 66 in the summer of 2013, ba246c3e29a16ac9aad7337b2bb5b28ac2a71376, but Daren thought that it "should be" 60.  I guess that particular issue has been decided.
